### ISSUE TITLE
OpenGL 4.x support with OpenGLRawGen

### ISSUE THREAD

**Issue by wdanilo** [haskell-opengl/OpenGL#53]
Hello! Is it possible to update the OpenGL package to use OpenGL 4.x with OpenGLRawgen (https://github.com/Laar/OpenGLRawgen) bindings under the hood?
OGL 3.2 is very outdated right now and it would be nice to allow Haskell users use newer libs.

**Comment by svenpanne** [comment]
The current OpenGLRaw package offers the whole OpenGL API (4.5 plus all extensions), generated from the XML registry. I'll expose more and more of the missing functionality in the OpenGL package, but if you really need something desperately, pull requests are happily accepted. (<- Hint! :wink: ) Furthermore, you can always use stuff from OpenGLRaw directly in conjunction with OpenGL.

I think closing this issue is the right thing to do now, if you need some concrete functionality, please open a separate, more concrete bug.
