### ISSUE TITLE
Compatibility with GHC 9.2 and transformers 0.6

### ISSUE THREAD

**Issue by sjakobi** [haskell-opengl/OpenGL#89]
`master` already seems to build with GHC 9.2 – could you make a release or a revision?

Compatibility with the latest `transformers` will require another bump (and possibly code changes – I didn't check).

**Comment by ulysses4ever** [comment]
@svenpanne @dagit would it be possible to have a Hackage revision? It seems like it's "only" a matter of bumping the `bytestring`'s bound.

**Comment by andreasabel** [comment]
I revised the outdated upper bounds on Hackage: https://hackage.haskell.org/package/OpenGL-3.0.3.0/revisions/
I tested compilation with GHC 8.8.4, 8.10.7, 9.0.2, 9.2.3 and 9.4.1 (alpha2).  The last one requires `--allow-newer` for dependency `OpenGLRaw`.
I hope this revision is ok with you Sven @SvenPanne, let me know otherwise.
